### ISSUE TITLE
làm cánh nào để lấy được streaming video ah

### ISSUE THREAD

**Issue by Trung123580** [phamhiep2506/zingmp3-api-full#2]
Em đang khó trong việc làm chức năng next video và endvideo vì nếu dùng trong mảng danh sách để next video thì nó sẽ call lại api vì id của nó thay đổi thì cái mảng danh sách sẽ được làm mới và nếu dùng tiếp nó sẽ sai kết quả và có khả năng lặp lại video trước đó, nên có cái nào giống với get song/streaming không ah tách nó ra để có link video.
Em cảm ơn !

**Comment by phamhiep2506** [comment]
Sorry, Project này không còn được duy trì & fix lỗi.
